version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-p'password'"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: myfastapi-server
    env_file:
      - server/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
    networks:
      - app-network
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mystreamlit-client
    env_file:
      - client/.env
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./client:/app
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local